name: Deploy to Azure

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and Build
        # This tells the runner to look inside the folder where your package.json actually lives
        working-directory: ./tailwind-landing-page-template
        run: |
          npm install
          npm run build

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to Azure Storage
        run: |
          az storage blob upload-batch \
            --account-name twstorage1774621402 \
            --source tailwind-landing-page-template/out \
            --destination '$web' \
            --overwrite